org.gradle.jvmargs=-Xmx3G
org.gradle.caching=true
org.gradle.parallel=true
org.gradle.configureondemand=true
org.gradle.configuration-cache=false
net.minecraftforge.gradle.merge-source-sets=true

minecraft_version=26.1.1
forge_version=63.0.1

mod_id=mujmod
mod_name=MujMod
mod_license=MIT
mod_version=1.0.0
mod_authors=YourName
mod_description=My first Minecraft mod.
